CREATE TABLE SET_A (
 id int NOT NULL, 
 PRIMARY KEY (id)
);

INSERT INTO SET_A VALUES ( 1 );
INSERT INTO SET_A VALUES ( 2 );
INSERT INTO SET_A VALUES ( 3 );
INSERT INTO SET_A VALUES ( 4 );
INSERT INTO SET_A VALUES ( 5 );
INSERT INTO SET_A VALUES ( 6 );

CREATE TABLE SET_B (
 id int NOT NULL, 
 PRIMARY KEY (id)
);

INSERT INTO SET_B VALUES ( 3 );
INSERT INTO SET_B VALUES ( 4 );
INSERT INTO SET_B VALUES ( 5 );
INSERT INTO SET_B VALUES ( 6 );
INSERT INTO SET_B VALUES ( 7 );
INSERT INTO SET_B VALUES ( 8 );

